spring.application.name=usuarios


spring.datasource.url=jdbc:mysql://mysql-graphixstory-duocuc-d2a7.h.aivencloud.com:23330/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_yu0F1SIHxKFobZy1qCZ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
